// Command inventory 生成 terminal byte source 静态审计 baseline
// （Phase 0 交付物：terminal-output-inventory.json）。
//
// 扫描 backend/cmd/aicli/ui 与 backend/cmd/aicli/commands 下 production
// .go 文件的 terminal-effect call sites（os.Stdout/os.Stderr/fmt.Print*/
// io.WriteString/Write/WriteString/TerminalOutput() 等），为每个命中记录
// source path、symbol、AST call-site fingerprint、diagnostic line、kind、
// owner、scope、branch predicate、reason、removal phase 与 expected
// TransactionKind。JSON 输出由仓库提交，后续 CI 对比基线。
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// InventoryEntry 是单个 call-site 的登记项。
type InventoryEntry struct {
	Source          string `json:"source"`          // 相对仓库根的 source path
	Symbol          string `json:"symbol"`          // 所在函数/方法名
	Line            int    `json:"line"`            // 诊断 line（1-based）
	Fingerprint     string `json:"fingerprint"`     // AST call-site 指纹
	Kind            string `json:"kind"`            // 终端 effect 类别
	Owner           string `json:"owner,omitempty"` // 责任团队/模块
	Scope           string `json:"scope,omitempty"` // process / session / test
	BranchPredicate string `json:"branch_predicate,omitempty"`
	Reason          string `json:"reason,omitempty"` // 为什么此 call site 存在
	RemovalPhase    string `json:"removal_phase,omitempty"`
	TransactionKind string `json:"transaction_kind,omitempty"`
	Classification  string `json:"classification"` // gateway-terminal-effect / semantic-reducer-input / command-plain / command-tty / process-compat-startup / diagnostic-stderr
}

// Inventory 是完整 baseline。
type Inventory struct {
	SchemaVersion  uint32           `json:"schema_version"`
	BaselineCommit string           `json:"baseline_commit"`
	GeneratedAt    string           `json:"generated_at"`
	ScannedDirs    []string         `json:"scanned_dirs"`
	Excluded       []string         `json:"excluded"`
	Entries        []InventoryEntry `json:"entries"`
}

func main() {
	root := flag.String("root", ".", "repository root")
	commit := flag.String("commit", "unknown", "baseline commit")
	out := flag.String("out", "terminal-output-inventory.json", "output path")
	verify := flag.Bool("verify", false, "re-scan and compare against existing baseline; exit 1 on drift")
	flag.Parse()

	inv := Inventory{
		SchemaVersion:  1,
		BaselineCommit: *commit,
		GeneratedAt:    fmt.Sprintf("generated by inventory tool"),
		ScannedDirs:    []string{"backend/cmd/aicli/ui", "backend/cmd/aicli/commands"},
	}

	for _, dir := range inv.ScannedDirs {
		abs := filepath.Join(*root, filepath.FromSlash(dir))
		_ = filepath.Walk(abs, func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return nil
			}
			if info.IsDir() {
				base := filepath.Base(path)
				if base == ".backups" || base == ".tmp" || base == "vendor" || base == "node_modules" {
					return filepath.SkipDir
				}
				return nil
			}
			if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
				return nil
			}
			rel, _ := filepath.Rel(*root, path)
			rel = filepath.ToSlash(rel)
			fset := token.NewFileSet()
			f, err := parser.ParseFile(fset, path, nil, 0)
			if err != nil {
				inv.Excluded = append(inv.Excluded, rel+": parse error")
				return nil
			}
			walkFuncs(fset, f, rel, func(symbol string, line int, fp, kind, branch string) {
				classification, reason, removalPhase, txKind := classifyEntry(rel, symbol, kind)
				e := InventoryEntry{
					Source:          rel,
					Symbol:          symbol,
					Line:            line,
					Fingerprint:     fp,
					Kind:            kind,
					Classification:  classification,
					Owner:           "ai-agent-runtime",
					Reason:          reason,
					RemovalPhase:    removalPhase,
					TransactionKind: txKind,
					BranchPredicate: branch,
				}
				inv.Entries = append(inv.Entries, e)
			})
			return nil
		})
	}

	sort.Slice(inv.Entries, func(i, j int) bool {
		if inv.Entries[i].Source != inv.Entries[j].Source {
			return inv.Entries[i].Source < inv.Entries[j].Source
		}
		return inv.Entries[i].Line < inv.Entries[j].Line
	})

	if *verify {
		existing, err := os.ReadFile(*out)
		if err != nil {
			fmt.Fprintf(os.Stderr, "verify: cannot read baseline %s: %v\n", *out, err)
			os.Exit(2)
		}
		var old Inventory
		if err := json.Unmarshal(existing, &old); err != nil {
			fmt.Fprintf(os.Stderr, "verify: baseline %s is invalid json: %v\n", *out, err)
			os.Exit(2)
		}
		newKeys := fingerprintSet(inv.Entries)
		oldKeys := fingerprintSet(old.Entries)
		var added, removed []string
		for k := range newKeys {
			if !oldKeys[k] {
				added = append(added, k)
			}
		}
		for k := range oldKeys {
			if !newKeys[k] {
				removed = append(removed, k)
			}
		}
		sort.Strings(added)
		sort.Strings(removed)
		if len(added) > 0 || len(removed) > 0 {
			for _, k := range added {
				fmt.Printf("added   %s\n", k)
			}
			for _, k := range removed {
				fmt.Printf("removed %s\n", k)
			}
			fmt.Printf("verify: baseline drift: +%d added, -%d removed (entry count %d -> %d)\n",
				len(added), len(removed), len(old.Entries), len(inv.Entries))
			os.Exit(1)
		}
		fmt.Printf("verify: baseline matches (%d entries)\n", len(inv.Entries))
		return
	}

	data, err := json.MarshalIndent(inv, "", "  ")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, data, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Printf("entries=%d excluded=%d -> %s\n", len(inv.Entries), len(inv.Excluded), *out)
}

// fingerprintSet 提取 call-site 指纹集合（fingerprint 已含 source:line:col）。
func fingerprintSet(entries []InventoryEntry) map[string]bool {
	out := make(map[string]bool, len(entries))
	for _, e := range entries {
		out[e.Fingerprint] = true
	}
	return out
}

// walkFuncs 遍历 AST，收集 terminal writer call sites。
func walkFuncs(fset *token.FileSet, f *ast.File, rel string, emit func(symbol string, line int, fp, kind, branch string)) {
	var curFunc string
	ast.Inspect(f, func(n ast.Node) bool {
		fd, ok := n.(*ast.FuncDecl)
		if ok {
			curFunc = fd.Name.Name
		}
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		fnName := callName(call.Fun)
		kind := ""
		switch {
		case fnName == "os.Stdout.Write" || fnName == "os.Stdout.WriteString":
			kind = "os.Stdout"
		case fnName == "os.Stderr.Write" || fnName == "os.Stderr.WriteString":
			kind = "os.Stderr"
		case fnName == "fmt.Print" || fnName == "fmt.Printf" || fnName == "fmt.Println":
			kind = fnName // 直接写 os.Stdout
		case fnName == "fmt.Fprint" || fnName == "fmt.Fprintf" || fnName == "fmt.Fprintln":
			kind = fnName // 参数可能是 stdout/stderr/terminal writer
		case fnName == "io.WriteString":
			kind = "io.WriteString"
		case fnName == "TerminalOutput":
			kind = "TerminalOutput()"
		case fnName == "NewTerminalBellWriter":
			kind = "NewTerminalBellWriter"
		default:
			// 其他 .Write/.WriteString 是中间 writer（builder/buffer/hash），
			// 不是 terminal 流向，不登记。
			return true
		}
		if kind == "" {
			return true
		}
		pos := fset.Position(call.Pos())
		symbol := curFunc
		if symbol == "" {
			symbol = "<file>"
		}
		fp := fmt.Sprintf("%s:%d:%d", rel, pos.Line, pos.Column)
		emit(symbol, pos.Line, fp, kind, "")
		return true
	})
}

// classifyEntry 按来源与符号模式给出保守分类（证据驱动，每条规则注明依据）。
//
// 默认 gateway-terminal-effect：交互渲染 effect，意向路径是经
// RenderOutputGateway 提交（含 fixed_bottom_surface 的 legacy paint 直写点
// ——它们是待退役的迁移债，分类记录的是意向路径而非当前路径）。
//
// 分类语义来自设计计划审计节
// （docs/plan/aicli-chat-render-intermediate-layer-design-plan.md:3714）：
// gateway-terminal-effect / semantic-reducer-input / command-plain /
// command-tty / process-compat-startup。diagnostic-stderr 是补充类：
// aicli_diag.go 注释明确将诊断日志划出迁移债清单（调试/日志路径而非交互
// 渲染 writer），单独标记以免与交互渲染债混淆；仍登记指纹以防新增直写。
func classifyEntry(rel, symbol, kind string) (classification, reason, removalPhase, transactionKind string) {
	switch {
	case strings.HasSuffix(rel, "aicli_diag.go"):
		// 依据 aicli_diag.go 文件注释：stderr 诊断输出不进入迁移债清单。
		return "diagnostic-stderr",
			"stderr 诊断输出（[aicli-diag]），调试/日志路径，非交互渲染",
			"", ""
	case strings.HasSuffix(rel, "ui/terminal.go") && (symbol == "emitControl" || symbol == "PrintAt"):
		// 依据设计计划 legacy terminal-control facade 行：production
		// TerminalOutput() 只留 startup/process-compat allowlist。
		// emitControl 是控制序列统一出口（process proxy 物理出口），
		// PrintAt 是 legacy fallback——两者即该 allowlist 的现存成员。
		return "process-compat-startup",
			"process TerminalOutput() 允许列表：控制序列统一出口/legacy fallback",
			"phase-6", "legacy_immediate"
	default:
		return "gateway-terminal-effect", "", "phase-6", "frame"
	}
}

func callName(fun ast.Expr) string {
	switch x := fun.(type) {
	case *ast.SelectorExpr:
		if id, ok := x.X.(*ast.Ident); ok {
			return id.Name + "." + x.Sel.Name
		}
		// 嵌套 selector（如 os.Stdout.Write）：递归展开保持全限定名，
		// 否则会丢失前缀导致 os.Stdout/os.Stderr 等匹配不上。
		if sel, ok := x.X.(*ast.SelectorExpr); ok {
			return callName(sel) + "." + x.Sel.Name
		}
		if call, ok := x.X.(*ast.CallExpr); ok {
			inner := callName(call.Fun)
			return inner + "." + x.Sel.Name
		}
		return x.Sel.Name
	case *ast.Ident:
		return x.Name
	default:
		return ""
	}
}
