// Command contractgen 由 internal/events 的事件契约注册表生成前端类型：
// frontend/src/types/runtime/event-contract.ts（方案 §4 Batch 2「事件契约单一真源」）。
//
// 用法（仓库根或 backend 下均可）：
//
//	go run ./backend/cmd/contractgen            # 生成
//	go run ./backend/cmd/contractgen -check     # 只校验生成物是否与注册表一致（CI/门禁用）
//
// 生成物是「注册表 → 前端」的单向投影：只允许改注册表（internal/events/contract.go）
// 后重新生成，不要手改生成物。前端侧引用生成物的模块见方案 §4 Batch 2 的落点表。
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	runtimeevents "github.com/wwsheng009/ai-agent-runtime/internal/events"
)

const generatedBanner = "// Code generated by backend/cmd/contractgen from internal/events/contract.go. DO NOT EDIT.\n"

func main() {
	check := flag.Bool("check", false, "只校验生成物与注册表一致（不一致时退出码 1），不写文件")
	out := flag.String("out", "", "输出路径；默认 <repo>/frontend/src/types/runtime/event-contract.ts")
	flag.Parse()

	target := strings.TrimSpace(*out)
	if target == "" {
		root, err := repoRoot()
		if err != nil {
			fail(err)
		}
		target = filepath.Join(root, "frontend", "src", "types", "runtime", "event-contract.ts")
	}
	target = filepath.Clean(target)

	content := render()
	if *check {
		existing, err := os.ReadFile(target)
		if err != nil {
			fail(fmt.Errorf("读取生成物失败（是否忘记生成？）：%w", err))
		}
		if !bytes.Equal(existing, []byte(content)) {
			fail(fmt.Errorf("%s 与 internal/events 注册表不一致；请运行 go run ./backend/cmd/contractgen 重新生成", target))
		}
		fmt.Printf("event-contract 生成物与注册表一致：%s\n", target)
		return
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		fail(err)
	}
	if err := os.WriteFile(target, []byte(content), 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("已生成 %s（%d 个类型）\n", target, len(runtimeevents.RegisteredEventTypes()))
}

// repoRoot 从当前工作目录向上找「同时含 frontend/package.json 与 backend/go.mod」的目录。
func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if fileExists(filepath.Join(dir, "frontend", "package.json")) && fileExists(filepath.Join(dir, "backend", "go.mod")) {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("未找到仓库根（需同时含 frontend/package.json 与 backend/go.mod）")
		}
		dir = parent
	}
}

func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "contractgen:", err)
	os.Exit(1)
}

// render 输出确定性的 TS 生成物：类型按字典序，通道按位序固定。
func render() string {
	types := runtimeevents.RegisteredEventTypes()

	var buf bytes.Buffer
	buf.WriteString(generatedBanner)
	buf.WriteString("\n")
	buf.WriteString("/**\n")
	buf.WriteString(" * 运行时事件契约（后端 internal/events/contract.go 注册表的投影）。\n")
	buf.WriteString(" *\n")
	buf.WriteString(" * 通道语义：\n")
	buf.WriteString(" * - session_store：落盘 ⇒ 实时（长轮询/SSE 回放）与回放都能看到；\n")
	buf.WriteString(" * - live_only：仅实时转发，不落盘（刷新即丢）；\n")
	buf.WriteString(" * - chat_bridge：chat SSE 帧桥（工具生命周期在对话流里实时建行）；\n")
	buf.WriteString(" * - tail_only：仅回合末尾巴补发。\n")
	buf.WriteString(" *\n")
	buf.WriteString(" * 空通道数组表示「已登记、当前无 chat 侧交付通道」：显式声明而非遗漏。\n")
	buf.WriteString(" */\n\n")

	buf.WriteString("export const RUNTIME_EVENT_CONTRACT_VERSION = \"1\";\n\n")

	fmt.Fprintf(&buf, "export const CHAT_SSE_EVENT_PREFIX = %q;\n\n", runtimeevents.ChatSSEEventPrefix)

	buf.WriteString("export type RuntimeEventChannel =\n")
	buf.WriteString("  | \"session_store\"\n  | \"live_only\"\n  | \"chat_bridge\"\n  | \"tail_only\";\n\n")

	buf.WriteString("export type RuntimeEventType =\n")
	for _, eventType := range types {
		fmt.Fprintf(&buf, "  | %q\n", eventType)
	}
	buf.WriteString(";\n\n")

	buf.WriteString("export const RUNTIME_EVENT_CHANNELS: Record<\n  RuntimeEventType,\n  readonly RuntimeEventChannel[]\n> = {\n")
	for _, eventType := range types {
		fmt.Fprintf(&buf, "  %q: [%s],\n", eventType, renderChannelList(eventType))
	}
	buf.WriteString("};\n\n")

	renderTypeList(&buf, "RUNTIME_EVENT_PERSISTED_TYPES", runtimeevents.ChannelSessionStore)
	renderTypeList(&buf, "RUNTIME_EVENT_LIVE_ONLY_TYPES", runtimeevents.ChannelLiveOnly)
	renderTypeList(&buf, "RUNTIME_EVENT_CHAT_BRIDGE_TYPES", runtimeevents.ChannelChatBridge)
	renderTypeList(&buf, "RUNTIME_EVENT_TAIL_ONLY_TYPES", runtimeevents.ChannelTailOnly)
	renderProvenanceTypeList(&buf, "RUNTIME_EVENT_PROVENANCE_TYPES")

	buf.WriteString("/** 返回类型的通道列表；未登记类型返回空数组（与后端 ChannelsFor 一致）。 */\n")
	buf.WriteString("export function runtimeEventChannels(\n  type: string,\n): readonly RuntimeEventChannel[] {\n")
	buf.WriteString("  return (\n")
	buf.WriteString("    RUNTIME_EVENT_CHANNELS[type as RuntimeEventType] ?? []\n")
	buf.WriteString("  );\n")
	buf.WriteString("}\n\n")

	buf.WriteString("/** 判断类型是否命中给定通道。 */\n")
	buf.WriteString("export function runtimeEventHasChannel(\n  type: string,\n  channel: RuntimeEventChannel,\n): boolean {\n")
	buf.WriteString("  return runtimeEventChannels(type).includes(channel);\n")
	buf.WriteString("}\n")

	return buf.String()
}

// renderChannelList 按固定位序输出通道字面量，保证生成物确定性。
func renderChannelList(eventType string) string {
	channels := runtimeevents.ChannelsFor(eventType)
	names := make([]string, 0, 4)
	if channels&runtimeevents.ChannelSessionStore != 0 {
		names = append(names, fmt.Sprintf("%q", runtimeevents.ChannelNameSessionStore))
	}
	if channels&runtimeevents.ChannelLiveOnly != 0 {
		names = append(names, fmt.Sprintf("%q", runtimeevents.ChannelNameLiveOnly))
	}
	if channels&runtimeevents.ChannelChatBridge != 0 {
		names = append(names, fmt.Sprintf("%q", runtimeevents.ChannelNameChatBridge))
	}
	if channels&runtimeevents.ChannelTailOnly != 0 {
		names = append(names, fmt.Sprintf("%q", runtimeevents.ChannelNameTailOnly))
	}
	return strings.Join(names, ", ")
}

func renderTypeList(buf *bytes.Buffer, constName string, channelSet runtimeevents.ChannelSet) {
	fmt.Fprintf(buf, "export const %s: readonly RuntimeEventType[] = [\n", constName)
	for _, eventType := range runtimeevents.TypesWithChannel(channelSet) {
		fmt.Fprintf(buf, "  %q,\n", eventType)
	}
	buf.WriteString("];\n\n")
}

// renderProvenanceTypeList 输出「类型维度上承载 provenance」的事件（注册表
// ProvenanceBearing）。载荷维度（source_refs / profile_source_refs）是运行期
// 判定，不在生成物里；前端据此把 provenance 承载事件排除出通用轨迹白名单。
func renderProvenanceTypeList(buf *bytes.Buffer, constName string) {
	fmt.Fprintf(buf, "export const %s: readonly RuntimeEventType[] = [\n", constName)
	for _, eventType := range runtimeevents.RegisteredEventTypes() {
		if !runtimeevents.IsProvenanceBearingEventType(eventType) {
			continue
		}
		fmt.Fprintf(buf, "  %q,\n", eventType)
	}
	buf.WriteString("];\n\n")
}
