// P1-7：workspace.panels.interactions 英文文案模块；形状由 zh-CN 同名模块经 index satisfies 编译期约束。
export const enWorkspacePanelsInteractions = {
  approval: {
    title: "Approval required",
    unknownTool: "unknown tool",
    approve: "Approve",
    deny: "Deny",
    explain: "Explain",
    explaining: "Generating explanation…",
    explanationFailed: "Couldn't generate an explanation: {{message}}",
    explanationSourceModel: "Generated by {{model}}",
    explanationSourceRules: "Rule-based explanation (no model call)",
    remember: "Remember this approval",
    rememberScopeLabel: "Remember scope",
    rememberScopeSession: "This session only",
    rememberScopeProject: "This project (survives new sessions)",
    rememberPattern: "Will remember: {{pattern}}",
    feedbackPlaceholder: "Note (optional, forwarded to the model)",
  },
  question: {
    title: "Answer needed",
    required: "Required",
    placeholder: "Type your answer…",
    submit: "Submit answer",
  },
  planReview: {
    title: "Plan awaiting decision",
    hint: "Review the plan, then approve, request changes, or quit plan mode.",
  },
  submitting: "Submitting…",
};
