// Code generated by backend/cmd/contractgen from internal/events/contract.go. DO NOT EDIT.

/**
 * 运行时事件契约（后端 internal/events/contract.go 注册表的投影）。
 *
 * 通道语义：
 * - session_store：落盘 ⇒ 实时（长轮询/SSE 回放）与回放都能看到；
 * - live_only：仅实时转发，不落盘（刷新即丢）；
 * - chat_bridge：chat SSE 帧桥（工具生命周期在对话流里实时建行）；
 * - tail_only：仅回合末尾巴补发。
 *
 * 空通道数组表示「已登记、当前无 chat 侧交付通道」：显式声明而非遗漏。
 */

export const RUNTIME_EVENT_CONTRACT_VERSION = "1";

export const CHAT_SSE_EVENT_PREFIX = "chat.sse.";

export type RuntimeEventChannel =
  | "session_store"
  | "live_only"
  | "chat_bridge"
  | "tail_only";

export type RuntimeEventType =
  | "agent.reclaimed"
  | "agent.turn.finished"
  | "agent.turn.started"
  | "approval_requested"
  | "approval_resolved"
  | "assistant.delta"
  | "assistant.image_progress"
  | "assistant.reasoning"
  | "assistant_delta"
  | "assistant_message"
  | "assistant_reasoning"
  | "backtrack_finished"
  | "backtrack_started"
  | "checkpoint_created"
  | "completion.requirement_recovery"
  | "context.preflight.compacted"
  | "context.preflight.failed"
  | "context.preflight.started"
  | "context.profile.injected"
  | "context.tool_schema.compacted"
  | "context.tool_schema.frozen"
  | "context_reconciled"
  | "hooks.stop_blocked"
  | "job_cancelled"
  | "job_finished"
  | "job_output"
  | "job_started"
  | "llm.max_output_tokens.escalated"
  | "llm.prompt_cache.backoff_applied"
  | "llm.prompt_cache.breaker_tripped"
  | "llm.provider.health_opened"
  | "llm.reasoning_only.guardrail_hit"
  | "llm.reasoning_only.recovered"
  | "llm.request.finished"
  | "llm.request.started"
  | "llm.retry"
  | "llm.retry.aggregated"
  | "llm_request_finished"
  | "llm_request_started"
  | "mailbox_received"
  | "main_agent.route_applied"
  | "main_agent.route_cleared"
  | "main_agent.route_cost_guard_tripped"
  | "main_agent.route_disabled_for_turn"
  | "main_agent.route_prediction_invalid"
  | "main_agent.route_prediction_unresolvable"
  | "patch.applied"
  | "patch.decision"
  | "plan_archive_failed"
  | "plan_mode_changed"
  | "plan_review_available"
  | "plan_review_requested"
  | "question_answered"
  | "question_asked"
  | "recall.performed"
  | "rewind_finished"
  | "rewind_started"
  | "session.checkpoint_persist_error"
  | "session.routing_changed"
  | "session_compact_completed"
  | "session_compact_failed"
  | "session_compact_skipped"
  | "session_compact_started"
  | "session_end"
  | "session_interrupted"
  | "session_start"
  | "subagent.batch.canceled"
  | "subagent.batch.circuit_open"
  | "subagent.batch.completed"
  | "subagent.batch.created"
  | "subagent.batch.failed"
  | "subagent.batch.orphaned"
  | "subagent.batch.progress"
  | "subagent.batch.started"
  | "subagent.batch.timed_out"
  | "subagent.completed"
  | "subagent.denied"
  | "subagent.progress"
  | "subagent.requires_write"
  | "subagent.route.resolved"
  | "subagent.started"
  | "subagent.suspension.unavailable"
  | "subagent.task.completed"
  | "subagent.task.started"
  | "tool.completed"
  | "tool.denied"
  | "tool.malformed_arguments.guardrail_hit"
  | "tool.malformed_arguments.recovered"
  | "tool.progress"
  | "tool.reduced"
  | "tool.requested"
  | "tool_finished"
  | "tool_loop.exploration_stall_observed"
  | "tool_loop.repeated_prompt_observed"
  | "tool_receipt_recorded"
  | "tool_receipt_replayed"
  | "tool_started"
  | "turn.resumed"
  | "turn.suspended"
;

export const RUNTIME_EVENT_CHANNELS: Record<
  RuntimeEventType,
  readonly RuntimeEventChannel[]
> = {
  "agent.reclaimed": ["session_store"],
  "agent.turn.finished": [],
  "agent.turn.started": [],
  "approval_requested": ["session_store"],
  "approval_resolved": ["session_store"],
  "assistant.delta": [],
  "assistant.image_progress": ["session_store"],
  "assistant.reasoning": ["session_store"],
  "assistant_delta": ["session_store"],
  "assistant_message": [],
  "assistant_reasoning": ["session_store"],
  "backtrack_finished": [],
  "backtrack_started": [],
  "checkpoint_created": ["session_store"],
  "completion.requirement_recovery": [],
  "context.preflight.compacted": [],
  "context.preflight.failed": [],
  "context.preflight.started": [],
  "context.profile.injected": ["session_store"],
  "context.tool_schema.compacted": [],
  "context.tool_schema.frozen": [],
  "context_reconciled": ["session_store"],
  "hooks.stop_blocked": [],
  "job_cancelled": [],
  "job_finished": [],
  "job_output": [],
  "job_started": [],
  "llm.max_output_tokens.escalated": [],
  "llm.prompt_cache.backoff_applied": [],
  "llm.prompt_cache.breaker_tripped": ["session_store"],
  "llm.provider.health_opened": ["session_store"],
  "llm.reasoning_only.guardrail_hit": [],
  "llm.reasoning_only.recovered": [],
  "llm.request.finished": [],
  "llm.request.started": [],
  "llm.retry": [],
  "llm.retry.aggregated": [],
  "llm_request_finished": [],
  "llm_request_started": [],
  "mailbox_received": [],
  "main_agent.route_applied": ["session_store"],
  "main_agent.route_cleared": ["session_store"],
  "main_agent.route_cost_guard_tripped": ["session_store"],
  "main_agent.route_disabled_for_turn": ["session_store"],
  "main_agent.route_prediction_invalid": ["session_store"],
  "main_agent.route_prediction_unresolvable": ["session_store"],
  "patch.applied": [],
  "patch.decision": [],
  "plan_archive_failed": [],
  "plan_mode_changed": [],
  "plan_review_available": [],
  "plan_review_requested": [],
  "question_answered": [],
  "question_asked": [],
  "recall.performed": ["session_store"],
  "rewind_finished": [],
  "rewind_started": [],
  "session.checkpoint_persist_error": [],
  "session.routing_changed": ["session_store"],
  "session_compact_completed": ["session_store"],
  "session_compact_failed": ["session_store"],
  "session_compact_skipped": ["session_store"],
  "session_compact_started": ["session_store"],
  "session_end": ["session_store"],
  "session_interrupted": ["session_store"],
  "session_start": ["session_store"],
  "subagent.batch.canceled": ["session_store", "tail_only"],
  "subagent.batch.circuit_open": [],
  "subagent.batch.completed": ["tail_only"],
  "subagent.batch.created": [],
  "subagent.batch.failed": ["session_store", "tail_only"],
  "subagent.batch.orphaned": ["session_store", "tail_only"],
  "subagent.batch.progress": ["live_only"],
  "subagent.batch.started": ["tail_only"],
  "subagent.batch.timed_out": ["session_store", "tail_only"],
  "subagent.completed": ["session_store", "tail_only"],
  "subagent.denied": [],
  "subagent.progress": ["live_only"],
  "subagent.requires_write": [],
  "subagent.route.resolved": ["session_store", "tail_only"],
  "subagent.started": ["tail_only"],
  "subagent.suspension.unavailable": ["session_store", "tail_only"],
  "subagent.task.completed": ["tail_only"],
  "subagent.task.started": ["tail_only"],
  "tool.completed": ["session_store", "chat_bridge"],
  "tool.denied": [],
  "tool.malformed_arguments.guardrail_hit": [],
  "tool.malformed_arguments.recovered": [],
  "tool.progress": ["live_only"],
  "tool.reduced": [],
  "tool.requested": ["session_store", "chat_bridge"],
  "tool_finished": [],
  "tool_loop.exploration_stall_observed": [],
  "tool_loop.repeated_prompt_observed": [],
  "tool_receipt_recorded": [],
  "tool_receipt_replayed": [],
  "tool_started": [],
  "turn.resumed": ["session_store", "tail_only"],
  "turn.suspended": ["session_store", "tail_only"],
};

export const RUNTIME_EVENT_PERSISTED_TYPES: readonly RuntimeEventType[] = [
  "agent.reclaimed",
  "approval_requested",
  "approval_resolved",
  "assistant.image_progress",
  "assistant.reasoning",
  "assistant_delta",
  "assistant_reasoning",
  "checkpoint_created",
  "context.profile.injected",
  "context_reconciled",
  "llm.prompt_cache.breaker_tripped",
  "llm.provider.health_opened",
  "main_agent.route_applied",
  "main_agent.route_cleared",
  "main_agent.route_cost_guard_tripped",
  "main_agent.route_disabled_for_turn",
  "main_agent.route_prediction_invalid",
  "main_agent.route_prediction_unresolvable",
  "recall.performed",
  "session.routing_changed",
  "session_compact_completed",
  "session_compact_failed",
  "session_compact_skipped",
  "session_compact_started",
  "session_end",
  "session_interrupted",
  "session_start",
  "subagent.batch.canceled",
  "subagent.batch.failed",
  "subagent.batch.orphaned",
  "subagent.batch.timed_out",
  "subagent.completed",
  "subagent.route.resolved",
  "subagent.suspension.unavailable",
  "tool.completed",
  "tool.requested",
  "turn.resumed",
  "turn.suspended",
];

export const RUNTIME_EVENT_LIVE_ONLY_TYPES: readonly RuntimeEventType[] = [
  "subagent.batch.progress",
  "subagent.progress",
  "tool.progress",
];

export const RUNTIME_EVENT_CHAT_BRIDGE_TYPES: readonly RuntimeEventType[] = [
  "tool.completed",
  "tool.requested",
];

export const RUNTIME_EVENT_TAIL_ONLY_TYPES: readonly RuntimeEventType[] = [
  "subagent.batch.canceled",
  "subagent.batch.completed",
  "subagent.batch.failed",
  "subagent.batch.orphaned",
  "subagent.batch.started",
  "subagent.batch.timed_out",
  "subagent.completed",
  "subagent.route.resolved",
  "subagent.started",
  "subagent.suspension.unavailable",
  "subagent.task.completed",
  "subagent.task.started",
  "turn.resumed",
  "turn.suspended",
];

export const RUNTIME_EVENT_PROVENANCE_TYPES: readonly RuntimeEventType[] = [
  "context.profile.injected",
  "recall.performed",
];

/** 返回类型的通道列表；未登记类型返回空数组（与后端 ChannelsFor 一致）。 */
export function runtimeEventChannels(
  type: string,
): readonly RuntimeEventChannel[] {
  return (
    RUNTIME_EVENT_CHANNELS[type as RuntimeEventType] ?? []
  );
}

/** 判断类型是否命中给定通道。 */
export function runtimeEventHasChannel(
  type: string,
  channel: RuntimeEventChannel,
): boolean {
  return runtimeEventChannels(type).includes(channel);
}
