// Code generated by backend/cmd/contractgen from internal/events/contract.go. DO NOT EDIT.

/**
 * 运行时事件契约（后端 internal/events/contract.go 注册表的投影）。
 *
 * 通道语义：
 * - session_store：落盘 ⇒ 实时（长轮询/SSE 回放）与回放都能看到；
 * - live_only：仅实时转发，不落盘（刷新即丢）；
 * - chat_bridge：chat SSE 帧桥（工具生命周期在对话流里实时建行）；
 * - tail_only：仅回合末尾巴补发。
 *
 * 空通道数组表示「已登记、当前无 chat 侧交付通道」：显式声明而非遗漏。
 */

export const RUNTIME_EVENT_CONTRACT_VERSION = "1";

export const CHAT_SSE_EVENT_PREFIX = "chat.sse.";

export type RuntimeEventChannel =
  | "session_store"
  | "live_only"
  | "chat_bridge"
  | "tail_only";

export type RuntimeEventType =
  | "agent.reclaimed"
  | "approval_requested"
  | "approval_resolved"
  | "assistant.delta"
  | "assistant.image_progress"
  | "assistant.reasoning"
  | "assistant_delta"
  | "assistant_message"
  | "assistant_reasoning"
  | "backtrack_finished"
  | "backtrack_started"
  | "checkpoint_created"
  | "context.profile.injected"
  | "context_reconciled"
  | "job_cancelled"
  | "job_finished"
  | "job_output"
  | "job_started"
  | "llm_request_finished"
  | "llm_request_started"
  | "mailbox_received"
  | "question_answered"
  | "question_asked"
  | "recall.performed"
  | "rewind_finished"
  | "rewind_started"
  | "session.checkpoint_persist_error"
  | "session_compact_completed"
  | "session_compact_failed"
  | "session_compact_skipped"
  | "session_compact_started"
  | "session_end"
  | "session_interrupted"
  | "session_start"
  | "subagent.batch.completed"
  | "subagent.batch.started"
  | "subagent.completed"
  | "subagent.progress"
  | "subagent.started"
  | "tool.completed"
  | "tool.denied"
  | "tool.malformed_arguments.guardrail_hit"
  | "tool.malformed_arguments.recovered"
  | "tool.progress"
  | "tool.reduced"
  | "tool.requested"
  | "tool_finished"
  | "tool_receipt_recorded"
  | "tool_receipt_replayed"
  | "tool_started"
;

export const RUNTIME_EVENT_CHANNELS: Record<
  RuntimeEventType,
  readonly RuntimeEventChannel[]
> = {
  "agent.reclaimed": ["session_store"],
  "approval_requested": ["session_store"],
  "approval_resolved": ["session_store"],
  "assistant.delta": [],
  "assistant.image_progress": ["session_store"],
  "assistant.reasoning": ["session_store"],
  "assistant_delta": ["session_store"],
  "assistant_message": [],
  "assistant_reasoning": ["session_store"],
  "backtrack_finished": [],
  "backtrack_started": [],
  "checkpoint_created": ["session_store"],
  "context.profile.injected": ["session_store"],
  "context_reconciled": ["session_store"],
  "job_cancelled": [],
  "job_finished": [],
  "job_output": [],
  "job_started": [],
  "llm_request_finished": [],
  "llm_request_started": [],
  "mailbox_received": [],
  "question_answered": [],
  "question_asked": [],
  "recall.performed": ["session_store"],
  "rewind_finished": [],
  "rewind_started": [],
  "session.checkpoint_persist_error": [],
  "session_compact_completed": ["session_store"],
  "session_compact_failed": ["session_store"],
  "session_compact_skipped": ["session_store"],
  "session_compact_started": ["session_store"],
  "session_end": ["session_store"],
  "session_interrupted": ["session_store"],
  "session_start": ["session_store"],
  "subagent.batch.completed": ["tail_only"],
  "subagent.batch.started": ["tail_only"],
  "subagent.completed": ["tail_only"],
  "subagent.progress": ["live_only"],
  "subagent.started": ["tail_only"],
  "tool.completed": ["session_store", "chat_bridge"],
  "tool.denied": [],
  "tool.malformed_arguments.guardrail_hit": [],
  "tool.malformed_arguments.recovered": [],
  "tool.progress": ["live_only"],
  "tool.reduced": [],
  "tool.requested": ["session_store", "chat_bridge"],
  "tool_finished": [],
  "tool_receipt_recorded": [],
  "tool_receipt_replayed": [],
  "tool_started": [],
};

export const RUNTIME_EVENT_PERSISTED_TYPES: readonly RuntimeEventType[] = [
  "agent.reclaimed",
  "approval_requested",
  "approval_resolved",
  "assistant.image_progress",
  "assistant.reasoning",
  "assistant_delta",
  "assistant_reasoning",
  "checkpoint_created",
  "context.profile.injected",
  "context_reconciled",
  "recall.performed",
  "session_compact_completed",
  "session_compact_failed",
  "session_compact_skipped",
  "session_compact_started",
  "session_end",
  "session_interrupted",
  "session_start",
  "tool.completed",
  "tool.requested",
];

export const RUNTIME_EVENT_LIVE_ONLY_TYPES: readonly RuntimeEventType[] = [
  "subagent.progress",
  "tool.progress",
];

export const RUNTIME_EVENT_CHAT_BRIDGE_TYPES: readonly RuntimeEventType[] = [
  "tool.completed",
  "tool.requested",
];

export const RUNTIME_EVENT_TAIL_ONLY_TYPES: readonly RuntimeEventType[] = [
  "subagent.batch.completed",
  "subagent.batch.started",
  "subagent.completed",
  "subagent.started",
];

export const RUNTIME_EVENT_PROVENANCE_TYPES: readonly RuntimeEventType[] = [
  "context.profile.injected",
  "recall.performed",
];

/** 返回类型的通道列表；未登记类型返回空数组（与后端 ChannelsFor 一致）。 */
export function runtimeEventChannels(
  type: string,
): readonly RuntimeEventChannel[] {
  return (
    RUNTIME_EVENT_CHANNELS[type as RuntimeEventType] ?? []
  );
}

/** 判断类型是否命中给定通道。 */
export function runtimeEventHasChannel(
  type: string,
  channel: RuntimeEventChannel,
): boolean {
  return runtimeEventChannels(type).includes(channel);
}
